apiVersion: v1
kind: Service
metadata:
  name: k8s-api
  namespace: default
  labels:
    app: k8s-api
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30080 #service对外开放端口
  selector:
    app: k8s-api
---
apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
  name: k8s-api #名称
  labels:
    app: k8s-api #标注 
spec:
  replicas: 2 #运行容器的副本数，修改这里可以快速修改分布式节点数量
  selector:
    matchLabels:
      app: k8s-api
  template:
    metadata:
      labels:
        app: k8s-api
    spec:
      containers: #docker容器的配置
      - name: k8s-api
        image: docker.io/18322764663/k8s_api:latest # pull镜像的地址 ip:prot/dir/images:tag
        imagePullPolicy: IfNotPresent #pull镜像时机，
        ports:
        - containerPort: 8080 #容器对外开放端口