apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-k8s-api.fullname" . }}
  labels:
{{ include "helm-k8s-api.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    app.kubernetes.io/name: {{ include "helm-k8s-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
