apiVersion: v1
kind: Service
metadata:
  name: {{ template "mydemo.fullname" . }}
  namespace: default
  labels:
    app: {{ template "mydemo.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }} #service对外开放端口
  selector:
    app: {{ template "mydemo.fullname" . }}